* Generated by IBMABAP01 30.07.2010  12:57:06
INCLUDE MP900110.                      " Data Definitions
INCLUDE MPPDAT00.                      " Global Data     - Do not change
INCLUDE FP50PPSB.                      " Buffer          - Do not change
INCLUDE MPPERS00.                      " Standard Modules- Do not change
INCLUDE MP900120.                      " Output Modules
INCLUDE MP900130.                      " Input Modules
INCLUDE MP900140.                      " Subroutines

INCLUDE MP900150.
