*&---------------------------------------------------------------------*
*&  Include           Z6HRI_SELSCREEN1
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&  Include           ZHRI_SELSCREEN1
*&---------------------------------------------------------------------*

 SELECTION-SCREEN: BEGIN OF BLOCK blk WITH FRAME TITLE text-s01 ."NO INTERVALS .

  PARAMETERS   : pa_pernr TYPE pa0001-pernr OBLIGATORY.."
  PARAMETERS   : P_CHRONO TYPE CHAR15 OBLIGATORY..

 selection-screen end of block  blk.
 SELECTION-SCREEN: BEGIN OF BLOCK blk1 WITH FRAME TITLE text-s02 ."NO INTERVALS .
*offer letter j & o common 110 (11)
*34-Stipend Increase Memo-Apprentice & Trainee Engineer-J&O 129
 SELECTION-SCREEN BEGIN OF LINE.
 PARAMETERS : l1 RADIOBUTTON GROUP g1.
 SELECTION-SCREEN COMMENT 4(45) text-005  FOR FIELD  pa_pernr.
  SELECTION-SCREEN END OF LINE.

*offer letter-Manager 110 (11)
 SELECTION-SCREEN BEGIN OF LINE.
 PARAMETERS : l2 RADIOBUTTON GROUP g1.
 SELECTION-SCREEN COMMENT 4(45) text-006  FOR FIELD  pa_pernr.
  SELECTION-SCREEN END OF LINE.

*jms direct appointment kalwe 111 (12)
 SELECTION-SCREEN BEGIN OF LINE.
 PARAMETERS : l3 RADIOBUTTON GROUP g1.
 SELECTION-SCREEN COMMENT 4(45) text-007  FOR FIELD  pa_pernr.
  SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l5 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-009 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l6 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-030 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l7 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-031 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l8 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-032 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l9 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-033 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l10 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-034 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l11 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-035 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l12 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-036 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l13 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-037 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l14 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-038 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l15 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-039 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : l16 RADIOBUTTON GROUP g1.
SELECTION-SCREEN COMMENT 4(45) text-040 FOR FIELD pa_pernr.
SELECTION-SCREEN END OF LINE.


 SELECTION-SCREEN : END OF BLOCK blk1.
