*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 03.11.2010 at 12:57:42 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZ6HR_FG_OBJSTOP.                  " Global Data
  INCLUDE LZ6HR_FG_OBJSUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZ6HR_FG_OBJSF00                        . " subprograms
  INCLUDE LZ6HR_FG_OBJSI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZ6HR_FG_OBJSF...                  " Subprograms
* INCLUDE LZ6HR_FG_OBJSO...                  " PBO-Modules
* INCLUDE LZ6HR_FG_OBJSI...                  " PAI-Modules
