* 22.04.2005:  PCOK004060  STKU: Checkman
*3.0
* YMOK303366 290695 Matchcodereparatur (F4 auf Selektionsbild)
* YMOK139434 030495 neues Bezugsfeld für OBJID (PCHDY-OBJID_*)
* YMOK136846 210395 PCHWEGID setzen
* YMOK123741 170295 Selektionsbild
* YMOK115232 190195 Ausf. und drucken über Standard-Selektionsbild
* XFBK113656 100195 Parameter mit DDic-Bezug versehen
*2.2
* WARA097973 150894 Ausführen und Drucken für Vorreports.
************************************************************************
* RHXSBES0 Vorprogramm für ZRHSBES00
*  N762901  Clean up for Selection Screens
REPORT Z6HR041_HEADCOUNT MESSAGE-ID 5A.

TABLES: OBJEC.
TABLES: PCHDY.                                              "YMOK139434

INCLUDE RHSBESDT.
INCLUDE RHXMACRO.

RHX-INT-RADIO-DATA.

DATA: PRINT TYPE X VALUE '02'.

*SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME.            "PCOK004060
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME title text-sel.
PARAMETERS:
  PCHPLVAR LIKE PCHDY-PLVAR NO-DISPLAY,"Planvariante
  PCHOTYPE LIKE PCHDY-OTYPE NO-DISPLAY."Objekttyp
* ObjId
SELECT-OPTIONS:
* pchobjid for objec-objid.                         "ObjektId"YMOK139434
  PCHOBJID FOR PCHDY-OBJID_STR NO INTERVALS.        "ObjektId"YMOK139434
* Search
PARAMETERS:
  PCHSEARK LIKE PCHDY-SEARK."matchcode object plom."Suchbeg."YMOK303366
RHX-F4-OBJID-DATA.                                          "YMOK303366
* Path
PARAMETERS:
  PCHWEGID LIKE PCHDY-WEGID NO-DISPLAY.

* Objecttime
PARAMETERS:
  PCHOBEG  LIKE PCHDY-OBEG DEFAULT SY-DATUM.
PARAMETERS:
  PCHOEND  LIKE PCHDY-OEND NO-DISPLAY.
PARAMETERS :
  PCHTIMED LIKE PCHDY-TIMED NO-DISPLAY.
* Objectstate
RHX-OSTAT-DEFINE.
PARAMETERS:
  PCHBEGDA LIKE PCHDY-BEGDA NO-DISPLAY.
PARAMETERS:
  PCHENDDA LIKE PCHDY-ENDDA NO-DISPLAY.

PARAMETERS: ACC_STR  LIKE PDBES-ACC_STR DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-LOS.
SELECTION-SCREEN BEGIN OF LINE.
*SELECTION-SCREEN COMMENT 1(30) TEXT-PER.                       "N762901
SELECTION-SCREEN COMMENT 1(30) TEXT-PER FOR FIELD $PERCK.       "N762901
PARAMETERS: $PERCK   LIKE PDBES-FREQ.  "time period of work time
SELECTION-SCREEN POSITION 36.
PARAMETERS: PER_TXT LIKE PP0E-PER_TXT MODIF ID TXT.
SELECTION-SCREEN END   OF LINE.
PARAMETERS: HOLDONLY LIKE PDBES-HOLDONLY.              "show only holder
PARAMETERS: ORG_P    LIKE PDBES-ORG_P. "show persons without position
SELECTION-SCREEN END OF BLOCK B2.


SELECTION-SCREEN SKIP.
*{   REPLACE        SBXK900030                                        1
*\PARAMETER SEL_BOX LIKE PP00-HR_VIA_SEL.
*--------------------------------------------------------------------*
*---<< S/4HANA >>---*
*--------------------------------------------------------------------*
* Changed On - Friday, October 12, 2018 13:36:00
* Changed By - ABAP01 - Bhushan Mehta
* Purpose    - Simplification list - Use PARAMETERS, not PARAMETER
* Solution   - Replace PARAMETERS with PARAMETER
* TR         - SBXK900030 - S4H:BM:Simplification List:03.10.2018
*--------------------------------------------------------------------*
  PARAMETERS: SEL_BOX LIKE PP00-HR_VIA_SEL.
*}   REPLACE

DATA: FIRST_FLAG TYPE C.
DATA: SUBRC      LIKE SY-SUBRC.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF SCREEN-GROUP1 = 'TXT'.
      SCREEN-INPUT = 0.
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR PCHOBJID-LOW.      "YMOK303366
  RHX-F4-OBJID-LOW PCHPLVAR PCHOTYPE PCHOBJID '' ''.        "YMOK303366

AT SELECTION-SCREEN ON VALUE-REQUEST FOR PCHOBJID-HIGH.     "YMOK303366
  RHX-F4-OBJID-HIGH PCHPLVAR PCHOTYPE PCHOBJID '' ''.       "YMOK303366

  IF FIRST_FLAG <> SPACE.
    CLEAR FIRST_FLAG.
    IF PCHWEGID IS INITIAL.
      CLEAR ACC_STR.
    ENDIF.
  ENDIF.
  RHX-OSTAT-PBO.

AT SELECTION-SCREEN ON PCHOBJID.
  PERFORM CHECK_OBJID_SIGN(RHXCHK00) USING PCHOBJID-SIGN.

AT SELECTION-SCREEN ON PCHOSTAT.
  PERFORM CHECK_OSTAT(RHXCHK00) USING PCHOSTAT.

AT SELECTION-SCREEN ON $PERCK.
  PERFORM CHECK_PERCK(ZRHSBES00) USING $PERCK PER_TXT SUBRC.
  IF SUBRC > 0.
    MESSAGE E699 WITH
              'Diese Arbeitszeitbasis ist nicht erlaubt'(EPK).
  ENDIF.

*AT SELECTION-SCREEN ON $MODE.
*  PERFORM CHECK_MODE(ZRHSBES00) USING $MODE MODE_TXT SUBRC.
*  IF SUBRC > 0.
*    MESSAGE E699 WITH
*              'Dieser Anzeigemodus ist nicht erlaubt'(EMD).
*  ENDIF.
*  IF $MODE = MODE_BATCH AND NOT LIST_FLG IS INITIAL.
*    CLEAR $MODE.
*    MESSAGE E699 WITH
*            'Anzeigemodus nur in Standardliste erlaubt'(DMS).
*  ENDIF.

AT SELECTION-SCREEN.
  PERFORM CHECK_PLVAR(RHXCHK00) USING PCHPLVAR.
  PERFORM CHECK_SEARK(RHXCHK00) TABLES PCHOBJID
                                USING  PCHSEARK PCHPLVAR PCHOTYPE.

  IF PCHOBJID-LOW EQ SPACE AND PCHOBJID-HIGH EQ SPACE.
    MESSAGE W231.
  ENDIF.
  RHX-OSTAT-PAI.

INITIALIZATION.
  PERFORM RE77S0(MSTT77S0) USING 'OTYPE' 'ORGEH' PCHOTYPE SUBRC.
  PERFORM RE77S0(MSTT77S0) USING 'WORKT' 'PERCK' $PERCK SUBRC.
  IF SUBRC > 0.
    MESSAGE S001 WITH 'T77S0' 'WORKT' 'PERCK' SPACE.
    $PERCK = MONTHLY.
  ENDIF.
  PERFORM CHECK_PERCK(ZRHSBES00) USING $PERCK PER_TXT SUBRC.

*  PERFORM CHECK_MODE(ZRHSBES00) USING $MODE MODE_TXT SUBRC.

  PCHWEGID = 'DUMMY'.
  FIRST_FLAG = 'X'.
  RHX-OSTAT-INIT.

START-OF-SELECTION.
  IF ACC_STR <> SPACE.
    PERFORM RE77S0(MSTT77S0) USING 'SBES '   'P_O-O'
                                   PCHWEGID  SUBRC.
    IF SUBRC > 0.
*     pchwegid = 'ORGEH'.                                     YMOK136846
      PERFORM RE77S0(MSTT77S0) USING 'PPWAY' 'SBORG' PCHWEGID SUBRC."YMO
    ENDIF.
  ELSE.
    CLEAR PCHWEGID.
  ENDIF.

  IF NOT SEL_BOX IS INITIAL.
    IF SY-SUBTY O PRINT.
      SUBMIT ZRHSBES00 TO SAP-SPOOL VIA SELECTION-SCREEN
         SPOOL PARAMETERS %_PRINT
         ARCHIVE PARAMETERS %_ARCHIVE
         WITHOUT SPOOL DYNPRO
         WITH PCHPLVAR EQ PCHPLVAR
         WITH PCHOTYPE EQ PCHOTYPE
         WITH PCHOBJID IN PCHOBJID
         WITH PCHOBEG  EQ PCHOBEG
         WITH PCHOEND  EQ PCHOBEG
         WITH PCHOSTAT EQ PCHOSTAT
         WITH PCHBEGDA EQ PCHOBEG
         WITH PCHENDDA EQ PCHOBEG
         WITH PCHISTAT EQ PCHOSTAT
         WITH PCHWEGID EQ PCHWEGID
         WITH $PERCK   EQ $PERCK
         WITH HOLDONLY EQ HOLDONLY
         WITH ORG_P    EQ ORG_P.
    ELSE.
      SUBMIT ZRHSBES00 VIA SELECTION-SCREEN
         WITH PCHPLVAR EQ PCHPLVAR
         WITH PCHOTYPE EQ PCHOTYPE
         WITH PCHOBJID IN PCHOBJID
         WITH PCHOBEG  EQ PCHOBEG
         WITH PCHOEND  EQ PCHOBEG
         WITH PCHOSTAT EQ PCHOSTAT
         WITH PCHBEGDA EQ PCHOBEG
         WITH PCHENDDA EQ PCHOBEG
         WITH PCHISTAT EQ PCHOSTAT
         WITH PCHWEGID EQ PCHWEGID
         WITH $PERCK   EQ $PERCK
         WITH HOLDONLY EQ HOLDONLY
         WITH ORG_P    EQ ORG_P.
    ENDIF.
  ELSE.
    IF SY-SUBTY O PRINT.
   SUBMIT ZRHSBES00 TO SAP-SPOOL
        SPOOL PARAMETERS %_PRINT
        ARCHIVE PARAMETERS %_ARCHIVE
        WITHOUT SPOOL DYNPRO
        WITH PCHPLVAR EQ PCHPLVAR
        WITH PCHOTYPE EQ PCHOTYPE
        WITH PCHOBJID IN PCHOBJID
        WITH PCHOBEG  EQ PCHOBEG
        WITH PCHOEND  EQ PCHOBEG
        WITH PCHOSTAT EQ PCHOSTAT
        WITH PCHBEGDA EQ PCHOBEG
        WITH PCHENDDA EQ PCHOBEG
        WITH PCHISTAT EQ PCHOSTAT
        WITH PCHWEGID EQ PCHWEGID
        WITH $PERCK   EQ $PERCK
        WITH HOLDONLY EQ HOLDONLY
        WITH ORG_P    EQ ORG_P.
    ELSE.
      SUBMIT ZRHSBES00 AND RETURN
         WITH PCHPLVAR EQ PCHPLVAR
         WITH PCHOTYPE EQ PCHOTYPE
         WITH PCHOBJID IN PCHOBJID
         WITH PCHOBEG  EQ PCHOBEG
         WITH PCHOEND  EQ PCHOBEG
         WITH PCHOSTAT EQ PCHOSTAT
         WITH PCHBEGDA EQ PCHOBEG
         WITH PCHENDDA EQ PCHOBEG
         WITH PCHISTAT EQ PCHOSTAT
         WITH PCHWEGID EQ PCHWEGID
         WITH $PERCK   EQ $PERCK
         WITH HOLDONLY EQ HOLDONLY
         WITH ORG_P    EQ ORG_P.
    ENDIF.
  ENDIF.
