*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 03.11.2010 at 12:57:42 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVI_T7IND3......................................*
FORM GET_DATA_ZVI_T7IND3.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM T7IND3 WHERE
(VIM_WHERETAB) .
    CLEAR ZVI_T7IND3 .
ZVI_T7IND3-MANDT =
T7IND3-MANDT .
ZVI_T7IND3-INDCD =
T7IND3-INDCD .
ZVI_T7IND3-ENDDA =
T7IND3-ENDDA .
ZVI_T7IND3-RFVAL =
T7IND3-RFVAL .
ZVI_T7IND3-CRVAL =
T7IND3-CRVAL .
ZVI_T7IND3-REFCD =
T7IND3-REFCD .
ZVI_T7IND3-BEGDA =
T7IND3-BEGDA .
    SELECT SINGLE * FROM T7IND1 WHERE
INDCD = T7IND3-INDCD .
    IF SY-SUBRC EQ 0.
    ENDIF.
    SELECT * FROM T7IND9 WHERE
REFCD = T7IND3-REFCD .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZVI_T7IND3.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVI_T7IND3 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVI_T7IND3.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVI_T7IND3-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM T7IND3 WHERE
  INDCD = ZVI_T7IND3-INDCD AND
  ENDDA = ZVI_T7IND3-ENDDA .
    IF SY-SUBRC = 0.
    DELETE T7IND3 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM T7IND3 WHERE
  INDCD = ZVI_T7IND3-INDCD AND
  ENDDA = ZVI_T7IND3-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR T7IND3.
    ENDIF.
T7IND3-MANDT =
ZVI_T7IND3-MANDT .
T7IND3-INDCD =
ZVI_T7IND3-INDCD .
T7IND3-ENDDA =
ZVI_T7IND3-ENDDA .
T7IND3-RFVAL =
ZVI_T7IND3-RFVAL .
T7IND3-CRVAL =
ZVI_T7IND3-CRVAL .
T7IND3-REFCD =
ZVI_T7IND3-REFCD .
T7IND3-BEGDA =
ZVI_T7IND3-BEGDA .
    IF SY-SUBRC = 0.
    UPDATE T7IND3 .
    ELSE.
    INSERT T7IND3 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVI_T7IND3-UPD_FLAG,
STATUS_ZVI_T7IND3-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVI_T7IND3.
  SELECT SINGLE * FROM T7IND3 WHERE
INDCD = ZVI_T7IND3-INDCD AND
ENDDA = ZVI_T7IND3-ENDDA .
ZVI_T7IND3-MANDT =
T7IND3-MANDT .
ZVI_T7IND3-INDCD =
T7IND3-INDCD .
ZVI_T7IND3-ENDDA =
T7IND3-ENDDA .
ZVI_T7IND3-RFVAL =
T7IND3-RFVAL .
ZVI_T7IND3-CRVAL =
T7IND3-CRVAL .
ZVI_T7IND3-REFCD =
T7IND3-REFCD .
ZVI_T7IND3-BEGDA =
T7IND3-BEGDA .
    SELECT SINGLE * FROM T7IND1 WHERE
INDCD = T7IND3-INDCD .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT * FROM T7IND9 WHERE
REFCD = T7IND3-REFCD .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVI_T7IND3 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVI_T7IND3-INDCD TO
T7IND3-INDCD .
MOVE ZVI_T7IND3-ENDDA TO
T7IND3-ENDDA .
MOVE ZVI_T7IND3-MANDT TO
T7IND3-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'T7IND3'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN T7IND3 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'T7IND3'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVI_T7IND3 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
T7IND3-MANDT =
ZVI_T7IND3-MANDT .
T7IND3-INDCD =
ZVI_T7IND3-INDCD .
T7IND3-ENDDA =
ZVI_T7IND3-ENDDA .
T7IND3-RFVAL =
ZVI_T7IND3-RFVAL .
T7IND3-CRVAL =
ZVI_T7IND3-CRVAL .
T7IND3-REFCD =
ZVI_T7IND3-REFCD .
T7IND3-BEGDA =
ZVI_T7IND3-BEGDA .
    SELECT SINGLE * FROM T7IND1 WHERE
INDCD = T7IND3-INDCD .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT * FROM T7IND9 WHERE
REFCD = T7IND3-REFCD .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
