*----------------------------------------------------------------------*
*   INCLUDE PCSANIN5                                                   *
*----------------------------------------------------------------------*

* SAN ID
SELECTION-SCREEN BEGIN OF BLOCK BOX1 WITH FRAME TITLE TEXT-001.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(30) TEXT-002 FOR FIELD SANID.
SELECTION-SCREEN POSITION 33.
PARAMETERS: SANID LIKE T7INS1-SANID OBLIGATORY.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BOX1.


* Customer Layout
SELECTION-SCREEN BEGIN OF BLOCK BOX2 WITH FRAME TITLE TEXT-003.

SELECTION-SCREEN PUSHBUTTON 2(17) LOUT USER-COMMAND LOUT.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 2(28) TEXT-004 FOR FIELD LAYOUT MODIF ID LOT.
SELECTION-SCREEN POSITION 31.
PARAMETERS:
  LAYOUT LIKE RSSCF-TDFORM MODIF ID LOT,
  LANGU LIKE RSSCF-TDSPRAS DEFAULT SY-LANGU MODIF ID LOT.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN:
BEGIN OF LINE,
COMMENT 2(15) TEXT-006 MODIF ID lot,
COMMENT 35(18) TEXT-052 FOR FIELD p_script MODIF ID lot,
POSITION 33.
PARAMETERS:
  p_script RADIOBUTTON GROUP r1 DEFAULT 'X' MODIF ID lot."For Scpt Displ
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN:
BEGIN OF LINE,
COMMENT 35(22) TEXT-051 FOR FIELD p_pdf MODIF ID lot,
POSITION 33.
PARAMETERS:
  p_pdf RADIOBUTTON GROUP r1 MODIF ID lot.       "For Pdf Display
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK BOX2.


***** START OF CHANGES FOR PDF FORM BY C5061983 '27-12-2004' *****

***** SELECTION SCREEN PART *****

*SELECTION-SCREEN : BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-006.
*
*PARAMETERS : P_PDF RADIOBUTTON GROUP RAD1 ,
*             P_SCRIPT RADIOBUTTON GROUP RAD1 DEFAULT 'X'.
*
*SELECTION-SCREEN END OF BLOCK BLK1.

***** END OF CHANGES FOR PDF FORM BY C5061983 '27-12-2004' *****
