*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 12.01.2013 at 12:47:10 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZ6HR039_ARR_REGTOP.               " Global Data
  INCLUDE LZ6HR039_ARR_REGUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZ6HR039_ARR_REGF00                     . " subprograms
  INCLUDE LZ6HR039_ARR_REGI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZ6HR039_ARR_REGF...               " Subprograms
* INCLUDE LZ6HR039_ARR_REGO...               " PBO-Modules
* INCLUDE LZ6HR039_ARR_REGI...               " PAI-Modules
