* INCLUDE PCEPFIN6 .

SELECTION-SCREEN:
  BEGIN OF BLOCK box0 WITH FRAME TITLE text-008.

* Trust Id
SELECTION-SCREEN:
  BEGIN OF LINE,
  COMMENT 1(30) text-100 FOR FIELD trust_id,
  POSITION 33.
PARAMETERS: trust_id LIKE t7inf7-tstid OBLIGATORY.
SELECTION-SCREEN END OF LINE.

select-options: s_bukrs for pa0001-bukrs. " IHDK902336

SELECTION-SCREEN END OF BLOCK box0.

DATA: on(1) VALUE '1',
      off(1) VALUE '0'.

SELECTION-SCREEN:
  BEGIN OF BLOCK box1 WITH FRAME TITLE text-001.

*Report-name
SELECTION-SCREEN:
  BEGIN OF LINE,
  COMMENT 1(30) text-009 FOR FIELD reponame,
  POSITION 33.
PARAMETERS:
reponame LIKE rpcepfin-repnm OBLIGATORY.
SELECTION-SCREEN END OF LINE.

*BankName
SELECTION-SCREEN:
  BEGIN OF LINE,
  COMMENT 1(30) text-011 FOR FIELD bankname,
  POSITION 33.
PARAMETERS:
bankname LIKE rpcepfin-bknam.
SELECTION-SCREEN END OF LINE.

* BankAddr
SELECTION-SCREEN:
  BEGIN OF LINE,
  COMMENT 1(30) text-012 FOR FIELD bankaddr,
  POSITION 33.
PARAMETERS:
bankaddr LIKE rpcepfin-bkadd.
SELECTION-SCREEN END OF LINE.

* BankCity
SELECTION-SCREEN:
  BEGIN OF LINE,
  COMMENT 1(30) text-013 FOR FIELD bankcity,
  POSITION 33.
PARAMETERS:
bankcity LIKE rpcepfin-bkcty.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN:
  BEGIN OF LINE,
  COMMENT 1(30) text-014 FOR FIELD repodate,
  POSITION 33.
PARAMETERS:
repodate LIKE rpcepfin-repdt DEFAULT sy-datum.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK box1.

SELECTION-SCREEN:
BEGIN OF BLOCK box2 WITH FRAME TITLE text-003.

SELECTION-SCREEN PUSHBUTTON 02(17) lout USER-COMMAND lout.

SELECTION-SCREEN:
BEGIN OF LINE,
  COMMENT 2(28) text-004 FOR FIELD layout MODIF ID lot,
  POSITION 33.
PARAMETERS:
  layout LIKE rsscf-tdform MODIF ID lot,
  langu LIKE rsscf-tdspras DEFAULT sy-langu MODIF ID lot.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN:
BEGIN OF LINE,
COMMENT 2(15) text-002 MODIF ID lot,
COMMENT 35(18) text-102 FOR FIELD p_script MODIF ID lot,
POSITION 33.
PARAMETERS:
  p_script RADIOBUTTON GROUP r1 DEFAULT 'X' MODIF ID lot."For Scpt Displ
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN:
BEGIN OF LINE,
COMMENT 35(22) text-101 FOR FIELD p_pdf MODIF ID lot,
POSITION 33.
PARAMETERS:
  p_pdf RADIOBUTTON GROUP r1 MODIF ID lot.       "For Pdf Display
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK box2.


***** START OF CHANGES FOR PDF FORM BY C5061983 '30-12-2004' *****

***** SELECTION SCREEN PART *****

*SELECTION-SCREEN : BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-002.
*
*PARAMETERS : P_PDF RADIOBUTTON GROUP RAD1 ,
*             P_SCRIPT RADIOBUTTON GROUP RAD1 DEFAULT 'X'.
*
*SELECTION-SCREEN END OF BLOCK BLK1.

***** END OF CHANGES FOR PDF FORM BY C5061983 '30-12-2004' *****


AT SELECTION-SCREEN ON VALUE-REQUEST FOR reponame.
  PERFORM show_formnames.
