*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 21.10.2010 at 15:11:15 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZEMPGRADETOP.                     " Global Data
  INCLUDE LZEMPGRADEUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZEMPGRADEF00                           . " subprograms
  INCLUDE LZEMPGRADEI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZEMPGRADEF...                     " Subprograms
* INCLUDE LZEMPGRADEO...                     " PBO-Modules
* INCLUDE LZEMPGRADEI...                     " PAI-Modules
