*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 16.04.2011 at 10:38:53 by user IBMABAP01
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZF16_WAGETYPESTOP.                " Global Data
  INCLUDE LZF16_WAGETYPESUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZF16_WAGETYPESF00                      . " subprograms
  INCLUDE LZF16_WAGETYPESI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZF16_WAGETYPESF...                " Subprograms
* INCLUDE LZF16_WAGETYPESO...                " PBO-Modules
* INCLUDE LZF16_WAGETYPESI...                " PAI-Modules
