*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 28.01.2013 at 11:41:06 by user 10106
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPPL_SFTTOP.                      " Global Data
  INCLUDE LZPPL_SFTUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPPL_SFTF00                            . " subprograms
  INCLUDE LZPPL_SFTI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPPL_SFTF...                      " Subprograms
* INCLUDE LZPPL_SFTO...                      " PBO-Modules
* INCLUDE LZPPL_SFTI...                      " PAI-Modules
